package com.coder.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.addr
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.job
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sal
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    private Integer sal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.addr
     *
     * @return the value of employee.addr
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.addr
     *
     * @param addr the value for employee.addr
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.job
     *
     * @return the value of employee.job
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.job
     *
     * @param job the value for employee.job
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sal
     *
     * @return the value of employee.sal
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public Integer getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sal
     *
     * @param sal the value for employee.sal
     *
     * @mbg.generated Sun Nov 30 19:09:03 CST 2025
     */
    public void setSal(Integer sal) {
        this.sal = sal;
    }
}